server:
  port: 2000
spring:
  application:
    name: crowd-mysql
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.56.102:3306/project_crowd?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: avamasterA@#
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
mybatis:
  mapper-locations: classpath*:/mybatis/mapper/*Mapper.xml
logging:
  level:
    com.company.crowd.mapper: debug
    com.company.crowd.test: debug